version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"

  web:
    build: .
    command: sh -c "/usr/local/bin/wait-for-it.sh db:${DATABASE_PORT} -- python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:${APPLICATION_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER} 
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}

volumes:
  db_data:
